package database

import (
	"database/sql"
	"time"
)

// CreateSession stores a browser session token with its owning user and expiry time.
func CreateSession(db *sql.DB, sessionID string, userID int, expiresAt time.Time) error {

	// The session ID is generated by the handler and becomes the cookie value.
	query := "INSERT INTO sessions (id, user_id, expires_at) VALUES(?, ?, ?)"

	// Store the expiry in the row so later lookups can reject stale cookies.
	_, err := db.Exec(query, sessionID, userID, expiresAt)
	if err != nil {
		return err
	}

	// Callers only need to know whether the session was persisted.
	return nil
}

// GetUserIDBySessionID returns the active user ID for a session token, or zero when it is missing or expired.
func GetUserIDBySessionID(db *sql.DB, sessionID string) (int, error) {

	// The expiry check lives in SQL so expired sessions behave the same as
	// unknown tokens to callers.
	query := `
		SELECT user_id
		FROM sessions
		WHERE id = ? AND expires_at > CURRENT_TIMESTAMP
	`
	row := db.QueryRow(query, sessionID)

	var userID int

	err := row.Scan(&userID)
	if err != nil {
		// Missing or expired sessions are authentication misses, not database failures.
		if err == sql.ErrNoRows {
			return 0, nil
		}
		return 0, err
	}

	return userID, nil
}

// DeleteSession removes a stored session token during logout.
func DeleteSession(db *sql.DB, sessionID string) error {

	// Deleting by opaque token lets logout invalidate only the current browser session.
	query := "DELETE FROM sessions WHERE id = ?"

	_, err := db.Exec(query, sessionID)
	if err != nil {
		return err
	}

	// DELETE without a matching row is still successful for logout cleanup.
	return nil
}

// DeleteSessionsByUserID removes all sessions for a user, which is useful after password changes.
func DeleteSessionsByUserID(db *sql.DB, userID int) error {
	query := "DELETE FROM sessions WHERE user_id = ?"

	_, err := db.Exec(query, userID)
	if err != nil {
		return err
	}

	return nil
}

// DeleteExpiredSessions removes stale sessions that can no longer authenticate requests.
func DeleteExpiredSessions(db *sql.DB) error {

	// Compare against SQLite's current timestamp so cleanup uses the same clock
	// basis as GetUserIDBySessionID.
	query := `
		DELETE FROM sessions
		WHERE expires_at <= CURRENT_TIMESTAMP
	`
	_, err := db.Exec(query)
	if err != nil {
		return err
	}

	// Callers do not need the count of removed rows.
	return nil
}
